server:
  port: 8081

spring:

  # Подключение к H2 бд через jdbc
  datasource:
    url: jdbc:h2:mem:testdb

  # Включение консоли
  h2:
    console:
      #enabled: false
      enabled: true

  # Включение liquibase и установка основного файла
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml